FROM node:22-bullseye

WORKDIR /usr/src/
COPY . honeycomb-opentelemetry-react-native

WORKDIR /usr/src/honeycomb-opentelemetry-react-native

WORKDIR /usr/src/honeycomb-opentelemetry-react-native/example
EXPOSE 8081
CMD [ "yarn", "start" ]
